server:
  port: 7080

spring:
  application:
    name: user-service

  # ????? OPCIONAL: JPA / DataSource ?????
  # jpa:
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQLDialect
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/billingapp_db
  #   username: postgres
  #   password: qwerty

  # ????? Spring Doc (OpenAPI) ?????
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

  # ????? Seguridad HTTP básica (solo admin) ?????
  security:
    user:
      name: admin
      password: qwerty
      # roles: ADMIN

  # ????? Desactivar Config Server opcional ?????
  cloud:
    config:
      enabled: false

# ????? Eureka Cliente ?????
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    healthcheck:
      enabled: true
    fetch-registry: true

# ????? Springdoc Properties adicionales ?????
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  packages-to-scan:
    - com.paymentchain.billing.entities
    - com.paymentchain.billing.controller
  paths-to-match:
    - /v1
    - /billing/**
