name: Lint commit messages
on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: commitlint.config.js
